[package]
name = "heapswap_core"
version = "0.1.0"
edition = "2021"

[dependencies]
# Local
heapswap_protos = { path = "../protos" }
# Crypto
crypto-bigint.workspace = true
num-bigint.workspace = true
rand.workspace = true
blake3.workspace = true
chacha20poly1305.workspace = true
curve25519-dalek.workspace = true
ed25519-dalek.workspace = true
x25519-dalek.workspace = true
# Encoding
base32.workspace = true
# Datastructures
bytes.workspace = true
# Serialization
serde.workspace = true
serde_bytes.workspace = true
bincode.workspace = true
prost.workspace = true
# Misc
derive_more.workspace = true
zeroize.workspace = true
derive-getters.workspace = true
#getset.workspace = true
timeit.workspace = true
num-traits.workspace = true
once_cell.workspace = true
